// Code generated by MockGen. DO NOT EDIT.
// Source: ./helper.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	resource "github.com/openshift/hive/pkg/resource"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
)

// MockHelper is a mock of Helper interface.
type MockHelper struct {
	ctrl     *gomock.Controller
	recorder *MockHelperMockRecorder
}

// MockHelperMockRecorder is the mock recorder for MockHelper.
type MockHelperMockRecorder struct {
	mock *MockHelper
}

// NewMockHelper creates a new mock instance.
func NewMockHelper(ctrl *gomock.Controller) *MockHelper {
	mock := &MockHelper{ctrl: ctrl}
	mock.recorder = &MockHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelper) EXPECT() *MockHelperMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockHelper) Apply(ctx context.Context, obj interface{}) (resource.ApplyState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", ctx, obj)
	ret0, _ := ret[0].(resource.ApplyState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Apply indicates an expected call of Apply.
func (mr *MockHelperMockRecorder) Apply(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockHelper)(nil).Apply), ctx, obj)
}

// Delete mocks base method.
func (m *MockHelper) Delete(ctx context.Context, gvk schema.GroupVersionKind, namespace, name string) (resource.DeleteState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, gvk, namespace, name)
	ret0, _ := ret[0].(resource.DeleteState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockHelperMockRecorder) Delete(ctx, gvk, namespace, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHelper)(nil).Delete), ctx, gvk, namespace, name)
}

// Patch mocks base method.
func (m *MockHelper) Patch(ctx context.Context, gvk schema.GroupVersionKind, namespace, name string, patch []byte, patchType types.PatchType) (resource.PatchState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", ctx, gvk, namespace, name, patch, patchType)
	ret0, _ := ret[0].(resource.PatchState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockHelperMockRecorder) Patch(ctx, gvk, namespace, name, patch, patchType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockHelper)(nil).Patch), ctx, gvk, namespace, name, patch, patchType)
}
