// Code generated by MockGen. DO NOT EDIT.
// Source: ./helper.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	resource "github.com/openshift/hive/pkg/resource"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// MockHelper is a mock of Helper interface.
type MockHelper struct {
	ctrl     *gomock.Controller
	recorder *MockHelperMockRecorder
}

// MockHelperMockRecorder is the mock recorder for MockHelper.
type MockHelperMockRecorder struct {
	mock *MockHelper
}

// NewMockHelper creates a new mock instance.
func NewMockHelper(ctrl *gomock.Controller) *MockHelper {
	mock := &MockHelper{ctrl: ctrl}
	mock.recorder = &MockHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelper) EXPECT() *MockHelperMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockHelper) Apply(ctx context.Context, obj interface{}) (resource.ApplyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", ctx, obj)
	ret0, _ := ret[0].(resource.ApplyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Apply indicates an expected call of Apply.
func (mr *MockHelperMockRecorder) Apply(ctx, obj interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockHelper)(nil).Apply), ctx, obj)
}

// Delete mocks base method.
func (m *MockHelper) Delete(ctx context.Context, gvk schema.GroupVersionKind, namespace, name string) (resource.DeleteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, gvk, namespace, name)
	ret0, _ := ret[0].(resource.DeleteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockHelperMockRecorder) Delete(ctx, gvk, namespace, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHelper)(nil).Delete), ctx, gvk, namespace, name)
}

// Patch mocks base method.
func (m *MockHelper) Patch(ctx context.Context, obj interface{}, patch []byte, opts ...resource.PatchOption) (resource.PatchResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, obj, patch}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Patch", varargs...)
	ret0, _ := ret[0].(resource.PatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockHelperMockRecorder) Patch(ctx, obj, patch interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, obj, patch}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockHelper)(nil).Patch), varargs...)
}

// PatchWithObject mocks base method.
func (m *MockHelper) PatchWithObject(ctx context.Context, gvk schema.GroupVersionKind, namespace, name string, patch []byte, opts ...resource.PatchOption) (resource.PatchResult, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, gvk, namespace, name, patch}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PatchWithObject", varargs...)
	ret0, _ := ret[0].(resource.PatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchWithObject indicates an expected call of PatchWithObject.
func (mr *MockHelperMockRecorder) PatchWithObject(ctx, gvk, namespace, name, patch interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, gvk, namespace, name, patch}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchWithObject", reflect.TypeOf((*MockHelper)(nil).PatchWithObject), varargs...)
}
