// Code generated by MockGen. DO NOT EDIT.
// Source: ./helper_v2.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	resource "github.com/openshift/hive/pkg/resource"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// MockHelperV2 is a mock of HelperV2 interface.
type MockHelperV2 struct {
	ctrl     *gomock.Controller
	recorder *MockHelperV2MockRecorder
}

// MockHelperV2MockRecorder is the mock recorder for MockHelperV2.
type MockHelperV2MockRecorder struct {
	mock *MockHelperV2
}

// NewMockHelperV2 creates a new mock instance.
func NewMockHelperV2(ctrl *gomock.Controller) *MockHelperV2 {
	mock := &MockHelperV2{ctrl: ctrl}
	mock.recorder = &MockHelperV2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelperV2) EXPECT() *MockHelperV2MockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockHelperV2) Apply(ctx context.Context, obj interface{}, opts ...resource.ApplyOption) (resource.ApplyResultV2, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, obj}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Apply", varargs...)
	ret0, _ := ret[0].(resource.ApplyResultV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Apply indicates an expected call of Apply.
func (mr *MockHelperV2MockRecorder) Apply(ctx, obj interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, obj}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockHelperV2)(nil).Apply), varargs...)
}

// Delete mocks base method.
func (m *MockHelperV2) Delete(ctx context.Context, gvk schema.GroupVersionKind, namespace, name string, opts ...resource.DeleteOption) (resource.DeleteResultV2, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, gvk, namespace, name}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(resource.DeleteResultV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockHelperV2MockRecorder) Delete(ctx, gvk, namespace, name interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, gvk, namespace, name}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHelperV2)(nil).Delete), varargs...)
}

// Patch mocks base method.
func (m *MockHelperV2) Patch(ctx context.Context, obj interface{}, patch []byte, opts ...resource.PatchOption) (resource.PatchResultV2, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, obj, patch}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Patch", varargs...)
	ret0, _ := ret[0].(resource.PatchResultV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockHelperV2MockRecorder) Patch(ctx, obj, patch interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, obj, patch}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockHelperV2)(nil).Patch), varargs...)
}

// PatchWithObject mocks base method.
func (m *MockHelperV2) PatchWithObject(ctx context.Context, gvk schema.GroupVersionKind, namespace, name string, patch []byte, opts ...resource.PatchOption) (resource.PatchResultV2, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, gvk, namespace, name, patch}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PatchWithObject", varargs...)
	ret0, _ := ret[0].(resource.PatchResultV2)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchWithObject indicates an expected call of PatchWithObject.
func (mr *MockHelperV2MockRecorder) PatchWithObject(ctx, gvk, namespace, name, patch interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, gvk, namespace, name, patch}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchWithObject", reflect.TypeOf((*MockHelperV2)(nil).PatchWithObject), varargs...)
}
