// Code generated by MockGen. DO NOT EDIT.
// Source: ./remoteclient.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	remoteclient "github.com/openshift/hive/pkg/remoteclient"
	dynamic "k8s.io/client-go/dynamic"
	kubernetes "k8s.io/client-go/kubernetes"
	rest "k8s.io/client-go/rest"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockBuilder is a mock of Builder interface.
type MockBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockBuilderMockRecorder
}

// MockBuilderMockRecorder is the mock recorder for MockBuilder.
type MockBuilderMockRecorder struct {
	mock *MockBuilder
}

// NewMockBuilder creates a new mock instance.
func NewMockBuilder(ctrl *gomock.Controller) *MockBuilder {
	mock := &MockBuilder{ctrl: ctrl}
	mock.recorder = &MockBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuilder) EXPECT() *MockBuilderMockRecorder {
	return m.recorder
}

// BuildDynamicWithContext mocks base method.
func (m *MockBuilder) BuildDynamicWithContext(ctx context.Context) (dynamic.Interface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildDynamicWithContext", ctx)
	ret0, _ := ret[0].(dynamic.Interface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildDynamicWithContext indicates an expected call of BuildDynamicWithContext.
func (mr *MockBuilderMockRecorder) BuildDynamicWithContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildDynamicWithContext", reflect.TypeOf((*MockBuilder)(nil).BuildDynamicWithContext), ctx)
}

// BuildKubeClientWithContext mocks base method.
func (m *MockBuilder) BuildKubeClientWithContext(ctx context.Context) (kubernetes.Interface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildKubeClientWithContext", ctx)
	ret0, _ := ret[0].(kubernetes.Interface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildKubeClientWithContext indicates an expected call of BuildKubeClientWithContext.
func (mr *MockBuilderMockRecorder) BuildKubeClientWithContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildKubeClientWithContext", reflect.TypeOf((*MockBuilder)(nil).BuildKubeClientWithContext), ctx)
}

// BuildWithContext mocks base method.
func (m *MockBuilder) BuildWithContext(ctx context.Context) (client.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildWithContext", ctx)
	ret0, _ := ret[0].(client.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildWithContext indicates an expected call of BuildWithContext.
func (mr *MockBuilderMockRecorder) BuildWithContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildWithContext", reflect.TypeOf((*MockBuilder)(nil).BuildWithContext), ctx)
}

// RESTConfigWithContext mocks base method.
func (m *MockBuilder) RESTConfigWithContext(ctx context.Context) (*rest.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RESTConfigWithContext", ctx)
	ret0, _ := ret[0].(*rest.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RESTConfigWithContext indicates an expected call of RESTConfigWithContext.
func (mr *MockBuilderMockRecorder) RESTConfigWithContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RESTConfigWithContext", reflect.TypeOf((*MockBuilder)(nil).RESTConfigWithContext), ctx)
}

// UsePrimaryAPIURL mocks base method.
func (m *MockBuilder) UsePrimaryAPIURL() remoteclient.Builder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsePrimaryAPIURL")
	ret0, _ := ret[0].(remoteclient.Builder)
	return ret0
}

// UsePrimaryAPIURL indicates an expected call of UsePrimaryAPIURL.
func (mr *MockBuilderMockRecorder) UsePrimaryAPIURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsePrimaryAPIURL", reflect.TypeOf((*MockBuilder)(nil).UsePrimaryAPIURL))
}

// UseSecondaryAPIURL mocks base method.
func (m *MockBuilder) UseSecondaryAPIURL() remoteclient.Builder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UseSecondaryAPIURL")
	ret0, _ := ret[0].(remoteclient.Builder)
	return ret0
}

// UseSecondaryAPIURL indicates an expected call of UseSecondaryAPIURL.
func (mr *MockBuilderMockRecorder) UseSecondaryAPIURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseSecondaryAPIURL", reflect.TypeOf((*MockBuilder)(nil).UseSecondaryAPIURL))
}
